### ISSUE TITLE
ChatUI [username] muss noch gesetzt werden

### ISSUE THREAD

**Issue by ScholliYT** [ScholliYT/NetworkChat#2]
Bein starten des ChatUIs wird der wirkliche Benutzername nicht geladen. Es wird einfach der statische String "ChatClinet [username]" geladen. 

Evtl. -> ein Statisches Datenfeld mit dem aktuellen Benutzernamen erstellen

**Comment by rueno** [comment]
Die Frage ist, ob man das in den Titel schreiben soll?
